### ISSUE TITLE
matlab-whole-body-simulator or matlab-whole-body-simulators ?

### ISSUE THREAD

**Issue by traversaro** [dic-iit/matlab-whole-body-simulator#17]
The repo name is matlab-whole-body-simulators, but the readme title is matlab-whole-body-simulator . 
What should we use @Giulero @nunoguedelha ?

**Comment by Giulero** [comment]
Since the simulator is one, I would say `matlab-whole-body-simulator` as repo name!

**Comment by traversaro** [comment]
Ok, I changed the name, for previous references (for example in deliverables) the redirect should work fine.
