### ISSUE TITLE
Run the simulator in MATLAB online with the robotology binaries installed through Conda

### ISSUE THREAD

**Issue by nunoguedelha** [dic-iit/matlab-whole-body-simulator#21]
We recently implemented changes for allowing the installation of this repository's dependencies using the [Robotology conda channel binaries](https://anaconda.org/robotology).

We wish to install and run the simulator on MATLAB online by using the type of commands explained in https://github.com/robotology/robotology-superbuild/pull/652#issuecomment-794027294.

With a MATLAB account, one can sign in and access to [MATLAB online](https://www.mathworks.com/products/matlab-online.html#connect-to-the-cloud), an online workspace that provides MATLAB and Simulink from any standard web browser. The GUI is practically identical to the one provided by the desktop application.

Once connected, the goal is to follow the procedure [-installing-the-dependencies-from-the-conda-robotology-channel](https://github.com/dic-iit/matlab-whole-body-simulator/tree/devel#floppy_disk-installing-the-dependencies-from-the-conda-robotology-channel) documented in the repository main README.md.

The steps will slightly differ from the ones in the referenced procedure because of the limitations of the bash provided by the MATLAB online session:
- The session `~/.bashrc` cannot be sourced (or sourcing it won't have any effect), so the **PATH** environment variable shall be set directly.
- No **Git** tool is available by default, so it has to be installed through **mamba**.
- any command run on terminal in the original procedure shall be run through the `system` instruction (refer to https://github.com/robotology/robotology-superbuild/pull/652#issuecomment-794027294).
- Any prompt resulting from those commands is not accessible from MATLAB, so we have to use the automatic "yes" user input (command option `-y`).

**Comment by nunoguedelha** [comment]
Once connected, we run the following steps. They can be encoded in a MATLAB script and we then could find a way to download it from this repository, without using git, and run it.

## Install the tools

1. Download the Miniforge installer
```
mkdir dev
cd dev
system('curl -LO https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh');
```
1. Install with default options
```
system('sh Miniforge3-Linux-x86_64.sh -b');
```
1. Add the conda binary to the PATH and check
```
setenv('PATH',['~/miniforge3/bin',':',getenv('PATH')]);
system('conda info');
```
1. Install Mamba
```
system('conda install -y mamba');
```
1. Install Git
```
system('mamba install -y git');
```
1. Clone the repository: shallow clone with a single branch 'devel' and latest commit on that branch
```
system('git clone --depth 1 https://github.com/dic-iit/matlab-whole-body-simulator --branch devel --single-branch');
```
## Get the repo files and install the dependencies

1. Install the conda binaries from the robotology channel.
   Using the `conda create/activate/deactivate` commands requires to run `conda init` and source the bashrc, which won't have any effect on MATLAB online. For that reason we have to install the conda binaries from the robotology channel on the **base** environment.
```
system('mamba install -y -c robotology iDynTree qpOASES icub-models wb-toolbox whole-body-controllers');
addpath('~/miniforge3/mex');
addpath('~/miniforge3/share/WBToolbox');
addpath('~/miniforge3/share/WBToolbox/images');
```

**Comment by nunoguedelha** [comment]
Implemented by #26

**Comment by nunoguedelha** [comment]
## Issues

- [ ] 1. Could not execute `configRobot.m` => File was not found because `YARP_ROBOT_NAME` was not set. FIXED.
- [ ] 2. Could not execute `yarp.Resource` => `yarp-matlab-bindings` dependency was missing. FIXED.
- [ ] 3. Failed to create Factory:

<img width="700" alt="image" src="https://user-images.githubusercontent.com/6848872/113498105-3e28b980-950a-11eb-96e4-bf198092f9d5.png">

**Comment by nunoguedelha** [comment]
CC @traversaro

**Comment by traversaro** [comment]
>  3. Failed to create Factory:

I think this should be fixed by setting `BLOCKFACTORY_PLUGIN_PATH` (see https://github.com/robotology/robotology-superbuild/blob/master/doc/environment-variables-configuration.md#dynamics) .

**Comment by nunoguedelha** [comment]
> I think this should be fixed by setting `BLOCKFACTORY_PLUGIN_PATH` (see https://github.com/robotology/robotology-superbuild/blob/master/doc/environment-variables-configuration.md#dynamics) .

I did this, and also set other environment variables that were not being set properly (which is normal since the `activate` command is not working I guess).
Setting `BLOCKFACTORY_PLUGIN_PATH` did not fix the problem.

Because the `conda activate <environment>` command is not working, I checked all the variables to be set and described in https://github.com/robotology/robotology-superbuild/blob/master/doc/environment-variables-configuration.md#dynamics. I added the following lines to the script:
```
setenv('YARP_DATA_DIRS',['~/miniforge3/share/yarp:~/miniforge3/share/iCub:',getenv('YARP_DATA_DIRS')]);
setenv('LD_LIBRARY_PATH',['~/miniforge3/lib:',getenv('LD_LIBRARY_PATH')]);
setenv('ROS_PACKAGE_PATH',['~/miniforge3/share:',getenv('ROS_PACKAGE_PATH')]);
setenv('BLOCKFACTORY_PLUGIN_PATH',[getenv('BLOCKFACTORY_PLUGIN_PATH'),':~/miniforge3/lib/blockfactory']);
```

**Comment by traversaro** [comment]
>  Setting `BLOCKFACTORY_PLUGIN_PATH` did not fix the problem.

Interesting, can you run `system('blockfactory-exists WBToolbox Jacobian')` and check the output?

**Comment by traversaro** [comment]
By the way, did you tried the full path instead of `~/miniforge3/lib/blockfactory` ? I do not know if `BLOCKFACTORY_PLUGIN_PATH` handles correctly the `~` .

**Comment by traversaro** [comment]
> 
> 
> By the way, did you tried the full path instead of `~/miniforge3/lib/blockfactory` ? I do not know if `BLOCKFACTORY_PLUGIN_PATH` handles correctly the `~` .

Yes, that's it:
~~~
>> setenv('BLOCKFACTORY_PLUGIN_PATH','~/miniforge3/lib/blockfactory');
>> system('blockfactory-exists WBToolbox Jacobian')
ERROR: Failed to get factory object (blockName=Jacobian,pluginName=WBToolbox)
ans =

     1

>> setenv('BLOCKFACTORY_PLUGIN_PATH','/home/mluser/miniforge3/lib/blockfactory');
>> system('blockfactory-exists WBToolbox Jacobian')
SUCCESS: Block "Jacobian" found and loaded from plugin "WBToolbox".

ans =

     0

>> 
~~~

**Comment by traversaro** [comment]
If you want to get the `~` value programmatically, you can as well:
~~~
>> [out, cmdout] = system('echo ~')

out =

     0


cmdout =

    '/home/mluser
     '

>> 
~~~

**Comment by traversaro** [comment]
For reference, this is the script I used to install the wb-toolbox on MATLAB Online:
~~~
system('rm ~/miniforge3')
system('curl -LO https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh')
system('sh Miniforge3-Linux-x86_64.sh -b')

system(['~/miniforge3/condabin/conda install -c robotology yarp-matlab-bindings idyntree wb-toolbox -y'])
addpath('~/miniforge3/mex')
setenv('PATH',['~/miniforge3/bin',':',getenv('PATH')]);
~~~

**Comment by traversaro** [comment]
> 
> 
> If you want to get the `~` value programmatically, you can as well:
> 
> ```
> >> [out, cmdout] = system('echo ~')
> 
> out =
> 
>      0
> 
> 
> cmdout =
> 
>     '/home/mluser
>      '
> 
> >> 
> ```

As suggested by @francesco-romano, a better strategy is just to use the `HOME` env variable: 
~~~
home_dir = getenv('HOME')
~~~

**Comment by nunoguedelha** [comment]
yes indeed!

**Comment by nunoguedelha** [comment]
It worked fine. Then I had a problem with Yarp Resource Finder finding the model URDF file but it was the same issue due to the `~` not properly handled.

**Comment by nunoguedelha** [comment]
Fixed `YARP_DATA_DIRS` and `ROS_PACKAGE_PATH` for adding the paths to the RRbot1 `model.urdf` and meshes path.

**Comment by nunoguedelha** [comment]
Issues 6. and 10. of https://github.com/dic-iit/matlab-whole-body-simulator/issues/21#issuecomment-812966647 do not prevent the simulation to run for a few seconds. At this point I think it's worth already reviewing the Pull Request #26 .

**Comment by traversaro** [comment]
As https://github.com/dic-iit/matlab-whole-body-simulator/pull/26 was merged, perhaps we can close this issue @nunoguedelha ?

**Comment by nunoguedelha** [comment]
> As #26 was merged, perhaps we can close this issue @nunoguedelha ?

I wanted to analyze this before closing this issue:
> (6) & (10) "Invalid value for (transformation) matrix property"

But we can also open a separate issue for that matter.

**Comment by nunoguedelha** [comment]
Done. issues 6 & 10 tracked in https://github.com/dic-iit/matlab-whole-body-simulator/issues/37.

Closing.
