### ISSUE TITLE
Fix issue with the meshes: convert from dae to stl

### ISSUE THREAD

**Issue by nunoguedelha** [dic-iit/matlab-whole-body-simulator#23]
We need to convert the Collada DAE format meshes to STL format meshes for completing the RRBot Gazebo example model. This is not a functional requirement, but only for visualization enhancement purposes, so low priority.

- [x] ~Converting Collada (.dae) to URDF (.stl)~ => at the end used an online converter https://3d-convert.com/en/convert/dae-to-stl.html.

  [Collada URDF](https://github.com/ros/collada_urdf) contains packages for converting from collada files to URDF. Collada to urdf command-line tool:
  ```
  rosrun collada_urdf collada_to_urdf <input.dae> <output.urdf>
  ```
  
  `collada_urdf` package has to be built and installed...
  
  - [x] Create a Catkin workspace, build catkin package and install in workspace (https://wiki.ros.org/catkin/Tutorials).
    
   > 1. Creating a workspace for catkin
   > 
   > 2. This tutorial covers how to setup a catkin workspace in which one or more catkin packages can be built.
   >    Creating a ROS Package
   > 
   > 3. How to create a new ROS package using catkin.
   >    Building and using catkin packages in a workspace
   > 
   > 4. How to use catkin_make to build and install packages from source in a catkin workspace.
   >    Overlaying with catkin workspaces
   > 
   > 5. Describes how to overlay a catkin workspace on to an existing system for development and testing. 

    - [x] Install `catkin` tools, from ROS packages (e.g. [robostack](https://github.com/RoboStack/ros-noetic)).
      Install [robostack](https://github.com/RoboStack/ros-noetic):
      ```
      conda create -n robostackenv python=3.8
      conda activate robostackenv
      conda config --env --add channels conda-forge
      conda config --env --add channels robostack
      conda config --env --set channel_priority strict
      mamba install ros-noetic-desktop
      mamba install compilers cmake pkg-config make ninja catkin_tools
      conda deactivate
      conda activate robostackenv
      ```

**Comment by traversaro** [comment]
> collada_urdf package has to be built and installed...

I think that that package converts a collada multibody model (that is different from an URDF model that use collada meshes) to a URDF model, to just convert a dae to an stl you can just use several available package online (see https://www.google.com/search?client=firefox-b-d&q=collada+to+stl) or software like meshlab.

**Comment by nunoguedelha** [comment]
Actually, I was interested anyway in trying the `robostack` packages, and a catkin workspacefor building ros packages in case it would be requiired in the future.

Regarding the collada files, I assumed that the collada multibody model was an all-in-one file including also the meshes. In such case, if applied to a .dae file having only a mesh, the tool would eventually generate an stl mesh in the conversion process. A lot of ifs, I know, but I was just going to give a quick try.

**Comment by traversaro** [comment]
> Actually, I was interested anyway in trying the `robostack` packages, and a catkin workspacefor building ros packages in case it would be requiired in the future.

Ack, however note that given that is not already built (see https://robostack.github.io/noetic.html) probably it has some kind of compilation failure.

**Comment by nunoguedelha** [comment]
> to just convert a dae to an stl you can just use several available package online

I've tried https://anyconv.com/dae-to-stl-converter and https://3d-convert.com/en/convert/dae-to-stl.html. The first generates a binary file, while the later generates text file which can easily be previewed with Quicklook for instance (on MacOS). I kept the later.

**Comment by traversaro** [comment]
> The first generates a binary file (which actually didn't work),

In the past to convert from binary to ascii STL I used https://github.com/cmpolis/convertSTL and it worked fine.

**Comment by nunoguedelha** [comment]
Also tried meshlab, installing with brew: "binary damaged" 😒
