### ISSUE TITLE
Create model integrating the YOGA++ controller with the dynamics with contacts simulator from matlab-whole-body-simulator

### ISSUE THREAD

**Issue by traversaro** [dic-iit/matlab-whole-body-simulator#32]
We wish to implement a Simulink model which controls a humanoid robot (iCub) performs a dynamic trajectory while balancing: the YOGA++. For that purpose, the model would integrate the YOGA++ controller with the whole-body simulator from `matlab-whole-body-simulator`.

**Comment by traversaro** [comment]
https://github.com/dic-iit/matlab-whole-body-simulator/issues/32

**Comment by nunoguedelha** [comment]
Task steps:
- [ ] Do a first test in `whole-body-controllers` replacing Gazebo by ["RobotDynWithContacts" + "IMU" + "robot visualizer"]
    - [ ] Create a "Robot Sensors" library and add a first "IMU" block.
    - [ ] Create a "Visualizers" library and add the existing "robot visualizer" block.
- [ ] Create a main model where the YOGA++ replaces the dummy one.

**Comment by nunoguedelha** [comment]
@traversaro , I've updated https://github.com/dic-iit/matlab-whole-body-simulator/issues/32#issuecomment-826775664 according to what we agreed in the meeting. Moving now the issue (manually) to `whole-body-controllers`.

**Comment by nunoguedelha** [comment]
Moved the issue to https://github.com/robotology/whole-body-controllers/issues/121. Closing this one.
