### ISSUE TITLE
Allow common `devel` and `master` commits history

### ISSUE THREAD

**Issue by nunoguedelha** [dic-iit/matlab-whole-body-simulator#52]
Hi @traversaro @Giulero @gabrielenava @CarlottaSartore .

So far, I have maintained two separate commits history, one for `devel` and one for `master`, and regularly merged `devel` to `master` or vice-versa. Usually, the `master` branch is for pushing fixes, and `devel` for implementing new features. This workflow is common in big projects, on repositories with many users and contributors. Sometimes we have both workflows, where `master` and `devel` can diverge temporarily but regularly converge to a single line of commits. In the case of this repository, the flow of issues and new features is quite slow for now and we could keep a workflow with a common commits history as often as possible. In such case, most merges between `devel` and `master` would be fast-forward when they don't diverge.

Do you guys have any opinion on this?

**Note:** There is also a new trend of renaming the `master` branch to `main` (https://about.gitlab.com/blog/2021/03/10/new-git-default-branch-name/). One of the repositories in robotology or dic-iit organizations adopted it, I don't remember which. I remember you being involved in this @traversaro , any news?

**Comment by traversaro** [comment]
> Do you guys have any opinion on this?

We have several project that only have a `master` branch and no `devel` . The `devel` branch in general is much less useful now that we release much more systematically and people interested in stability can use the releases.  So, feel free to just use ``master` as a single branch, this specific choice is up to the maintainer.

**Comment by gabrielenava** [comment]
> There is also a new trend of renaming the master branch to main (https://about.gitlab.com/blog/2021/03/10/new-git-default-branch-name/). One of the repositories in robotology or dic-iit organizations adopted it, I don't remember which

I've recently opened a new repo in the `dic` organization, and the default branch was `main` and not `master`. I don't know if you can choose between `main` and `master` or if the default branch is now `main`.

**Comment by traversaro** [comment]
> I don't know if for new repos you can choose between `main` and `master` or if the default branch is now `main`.

I think the default is now `main` (also at GitHub level) but you can still switch back to use `master` (as you can use any branch name).

**Comment by nunoguedelha** [comment]
I would then get rid of `devel`, keep only `master` and protect it (if it's not already the case).

But first let's cross-check with @CarlottaSartore nd @VenusPasandi if this doesn't disturb their workflow.

**Comment by CarlottaSartore** [comment]
Thanks @nunoguedelha  for the ping! Since we are working with tags, I do not think this would have an impact on our environment, do you agree @VenusPasandi ?

**Comment by VenusPasandi** [comment]
Thanks @nunoguedelha for your note! As @CarlottaSartore said we use a tag for this repo. So, it is fine for us.

**Comment by nunoguedelha** [comment]
Great! I'll proceed then.

**Comment by nunoguedelha** [comment]
Done.
- `devel` has been removed.
- `master` is now protected:
    - Branch deletion is not allowed to anyone.
    - Force-push is not allowed to anyone.
    - All PRs require at least one approving review before being merged.
    - A new review is required if a new commit is pushed.
    - All conversations resolution is required before merge.

**Note:** last commit in `devel` (2a553badd750e2d464d4def75c505da6efa01aa5) branch was a predecessor of current `master` branch commit, with exact same contents:

<img width="1156" alt="image" src="https://user-images.githubusercontent.com/6848872/121971117-49a12800-cd78-11eb-9dd6-b6bb9162c2c1.png">

**Comment by nunoguedelha** [comment]
This issue is ready to be closed.
